function [fpath,nickname] = exp_info

    nickname = {'VeryDeep2HR',  ...   %1
                'VD3D-P3',      ...   %2
                'MS-2D3D-v1',   ...   %3
                'MS-3D-v1',     ...   %4
                'VD2D3D-P3',    ...   %5
                'VD2D3D-P2',    ...   %6
                'VD2D3D-z9',    ...   %7
                'VD2D3D-z7',    ...   %8
                'VD2D3D-avg',   ...   %9
                'VD2D3D-MS',    ...   %10
                'VD2D3D-MS-pretrain'};%11

    root = get_workbench_root_path;

    fpath = { ...
        [root '/znn-release/experiments/Ashwin/3D_affinity/train23_test1/VeryDeep2HR_w65x9/rebalanced/eta02_out100/iter_30K/output/7nmTraining'], ...
        [root '/znn-release/experiments/Ashwin/3D_affinity/train23_test1/VD3D-P3_w69x13/exp1/iter_90K/output'], ...
        [root '/znn-release/experiments/Ashwin/3D_affinity/train234_test1/multiscale/MS-2D3D-v1/exp1/iter_100K/output'], ...
        [root '/znn-release/experiments/Ashwin/3D_affinity/train234_test1/multiscale/MS-3D-v1/exp2/iter_100K/output'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P3/exp1/iter_100K/exp1/iter_120K'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P2/exp2/iter_150K'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P1-F5/z9/exp1/iter_300K'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P1-F5/z7/exp1/iter_70K/exp1/iter_300K'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/avg/z9z7P2P3'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/MS/exp1/iter_150K'], ...
        [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/MS/pretrain/exp1/iter_200K/exp1/iter_300K']};

end