function [border] = get_border_mask_2D( slice )

    % Create border based on 4-neighbors connectivity.
    padded = padarray(slice, [1,1], 'replicate', 'both');
    border = (slice==padded(2:end-1,1:end-2)) & ...
             (slice==padded(2:end-1,3:end  )) & ...
             (slice==padded(1:end-2,2:end-1)) & ...
             (slice==padded(3:end,  2:end-1)) & ...
             (slice~=0);

end
