function [fpath] = exp_info

    % nickname = {'VeryDeep2HR',  ...   %1
    %             'VD3D-P3',      ...   %2
    %             'MS-2D3D-v1',   ...   %3
    %             'MS-3D-v1',     ...   %4
    %             'VD2D3D-P3',    ...   %5
    %             'VD2D3D-P2',    ...   %6
    %             'VD2D3D-z9',    ...   %7
    %             'VD2D3D-z7',    ...   %8
    %             'VD2D3D-avg',   ...   %9
    %             'VD2D3D-MS',    ...   %10
    %             'VD2D3D-MS-pretrain'};%11

    root = get_workbench_root_path;

    fpath = {[root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/MSF/exp1/iter_80K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P3/exp1/iter_100K/exp1/iter_120K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P2/exp2/iter_150K/exp1/iter_250K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P1-F5/z9/exp1/iter_300K/exp1/iter_500K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/P1-F5/z7/exp1/iter_70K/exp1/iter_300K/exp1/iter_500K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/avg/P3P2z7z9'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/avg/P3P2z7'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/avg/P3P2z9'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/MS/exp1/iter_150K'], ...
             [root '/seung-lab/znn-release/experiments/new_Piriform/VD2D3D/affinity/MS/pretrain/exp1/iter_200K/exp1/iter_300K'], ...
            };

end